services:
  - type: web
    name: keycloak-auth-service
    env: docker
    dockerfilePath: ./Dockerfile.keycloak
    plan: free
    region: singapore
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: Anjesh@123
      - key: KC_PROXY
        value: edge
      - key: KC_HTTP_ENABLED
        value: true
      - key: JAVA_OPTS
        value: -Xmx512m
    healthCheckPath: /
    autoDeploy: true