services:
  - type: web
    name: keycloak-auth-service
    env: docker
    dockerfilePath: ./Dockerfile.keycloak
    plan: free
    region: singapore
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: Anjesh@123
      - key: KC_PROXY
        value: edge
      - key: KC_HTTP_ENABLED
        value: true
      - key: JAVA_OPTS
        value: -Xmx512m
    healthCheckPath: /
    autoDeploy: true
  - type: web
    name: event-ticket-backend
    env: docker
    plan: free
    region: singapore
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DDL_AUTO
        value: update
      - key: KEYCLOAK_ISSUER_URI
        value: https://exs-d617tvgnputs73a745s0.onrender.com/realms/event-ticket-platform
      - key: DB_MAX_POOL_SIZE
        value: "10"
      - key: DB_MIN_IDLE
        value: "2"
      - key: DB_CONNECTION_TIMEOUT
        value: "30000"
      - key: DB_IDLE_TIMEOUT
        value: "600000"
      - key: DB_MAX_LIFETIME
        value: "1800000"
    healthCheckPath: /
    autoDeploy: true