services:
  - type: web
    name: keycloak-auth
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.keycloak
    region: ohio
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: Anjesh@123
      - key: KC_DB
        value: postgres
      - key: KC_HOSTNAME
        sync: false
      - key: KC_PROXY
        value: edge
      - key: KC_HTTP_ENABLED
        value: true
      - key: KC_HTTP_PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: false