services:
  - type: web
    name: keycloak-auth-service
    env: docker
    dockerfilePath: ./Dockerfile.keycloak
    plan: free
    region: singapore
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: Anjesh@123
      - key: KC_PROXY
        value: edge
      - key: KC_HTTP_ENABLED
        value: "true"
      - key: KC_HOSTNAME_STRICT
        value: "false"
      - key: KC_HOSTNAME
        value: keycloak-auth-service-2kac.onrender.com
      - key: KC_DB
        value: dev-file
      - key: KC_CACHE
        value: local
      - key: KC_HEALTH_ENABLED
        value: "true"
      - key: KC_METRICS_ENABLED
        value: "false"
      - key: KC_BOOTSTRAP_ADMIN_USER
        value: admin
      - key: KC_BOOTSTRAP_ADMIN_PASSWORD
        value: Anjesh@123
      - key: PORT
        value: 8080
    healthCheckPath: /health
    healthCheckProtocol: http
    healthCheckTimeout: 60
    healthCheckInterval: 15
    autoDeploy: true
  - type: web
    name: event-ticket-backend
    env: docker
    plan: free
    region: singapore
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DDL_AUTO
        value: update
      - key: KEYCLOAK_ISSUER_URI
        value: https://keycloak-auth-service-2kac.onrender.com/realms/event-ticket-platform
      - key: DB_MAX_POOL_SIZE
        value: "2"
      - key: DB_MIN_IDLE
        value: "1"
      - key: DB_CONNECTION_TIMEOUT
        value: "20000"
      - key: DB_IDLE_TIMEOUT
        value: "300000"
      - key: DB_MAX_LIFETIME
        value: "900000"
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: "-Xmx256m -XX:+UseG1GC -XX:+UseStringDeduplication"
    healthCheckPath: /actuator/health
    healthCheckProtocol: http
    healthCheckTimeout: 30
    healthCheckInterval: 15
    autoDeploy: true